services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: telegram_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql

  bot:
    image: mcr.microsoft.com/playwright/java:v1.62.0-noble
    container_name: find-job-telegram-bot
    working_dir: /app
    volumes:
      - .:/app
    command: ./gradlew run --no-daemon


volumes:
  postgres_data: