services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: telegram_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: